services:
  webserver:
    pull_policy: never
    container_name: webserver
    image: nginx:stable
    build:
      context: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./redaxo:/usr/share/nginx/html
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx/etc/server.conf:/etc/nginx/server.conf
    depends_on:
      - php
  php:
    pull_policy: never
    container_name: php
    build:
      context: php-fpm
      target: php-fpm-dev
    volumes:
      - ./redaxo:/var/www/html 
    depends_on:
      - db
  db:
    container_name: db
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: redaxouser
      MARIADB_PASSWORD: redaxouser
      MARIADB_DATABASE: redaxo