version: "3"
services:
  webserver:
    container_name: webserver
    image: nginx:stable
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx/etc/conf.d/default.conf:/etc/nginx/conf.d/default.conf

      - ./nginx/log:/var/log/nginx/
    depends_on:
      - php
  php:
    image: php:8-fpm
    container_name: php
    build:
      context: php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html 
      - ./php-fpm/log/:/var/log/php 
      - ./php-fpm/etc/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - db
  db:
    container_name: db
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: redaxouser
      MARIADB_PASSWORD: redaxouser
      MARIADB_DATABASE: redaxo
      
